# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FluentAssertions"
        versions: [ ">=8.0.0" ]
      - dependency-name: "Verify.MSTest"
        versions: [ ">=33.0.0" ]
    groups:
      Skyline-DataMiner-Dev:
        patterns:
          - "Skyline.DataMiner.Dev.*" 
      Skyline-DataMiner-Core:
        patterns:
          - "Skyline.DataMiner.Core.*"
