name: DataMiner CICD NuGet Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events.
  push:
    branches: 
      - '*'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

# Note: Tagging will push the nupackage to nuget.org using the provided NUGETAPIKEY. You can tag both a prerelease version (a.b.c-xxxx) or a stable release (a.b.c).
  CICD:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Master Workflow.yml@main
    with:
      sonarcloud-project-name: "SkylineCommunications_Skyline.DataMiner.Utils.DOM"
      nuget-push-source: "https://api.nuget.org/v3/index.json"
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
